import { useState } from 'react'
import type { Webtoon } from '../data/mockWebtoons'
import { minsuEpisode } from '../data/minsuEpisode'
type Props={item:Webtoon;onBack:()=>void}
const speakerNames=Object.fromEntries(minsuEpisode.characters.map(character=>[character.id,character.name]))
export default function WebtoonDetail({item,onBack}:Props){
 const[episode,setEpisode]=useState<number|null>(null)
 const[rating,setRating]=useState(0)
 const[review,setReview]=useState('')
 const[reviewSaved,setReviewSaved]=useState(false)
 const saveReview=()=>{if(!rating||!review.trim())return;localStorage.setItem('webtoon9.minsu.episode.' + (episode ?? 1) + '.review',JSON.stringify({rating,review:review.trim(),savedAt:new Date().toISOString()}));setReviewSaved(true)}
 if(item.id!==1)return <main className="detail-page"><button className="back-button" onClick={onBack}>← 목록으로</button><h1>{item.title}</h1><p>이 작품의 본문은 준비 중입니다.</p></main>
 const panels=Array.from({length:12},(_,index)=>({number:index+1,lines:minsuEpisode.dialogue.filter(line=>line.panel===index+1)}))
 if(episode===null)return <main className="detail-page episode-library"><button className="back-button" onClick={onBack}>← 작품 목록</button><header className="series-hero"><img src="/webtoon9/minsu-first-chance/scene-03.webp" alt={minsuEpisode.title}/><div><span>월요일 연재 · ORIGINAL</span><h1>{minsuEpisode.title}</h1><h2>{minsuEpisode.titleFr}</h2><p>{minsuEpisode.subtitle}</p><small>글·그림 {minsuEpisode.author}</small></div></header><section className="episode-list"><h2>회차</h2><button className="episode-item available" onClick={()=>setEpisode(1)}><img src="/webtoon9/minsu-first-chance/scene-01.webp" alt="1화"/><span><b>1화</b><small>민수의 첫 번째 기회</small></span><em>보기 ›</em></button></section></main>
 return <main className="detail-page original-comic"><button className="back-button" onClick={()=>setEpisode(null)}>← 회차 목록</button><div className="reader-episode-label">1화</div><section className="comic-reader">{panels.map(panel=><article className="comic-panel" key={panel.number}><img src={`/webtoon9/minsu-first-chance/scene-${String(panel.number).padStart(2,'0')}.webp`} alt={`${minsuEpisode.title} 장면 ${panel.number}`}/><div className="panel-dialogue">{panel.lines.map((line,index)=><div className="dialogue-line" key={`${panel.number}-${index}`}><strong>{speakerNames[line.speaker]??line.speaker}</strong><p lang="fr">{line.fr}</p></div>)}</div></article>)}</section><div className="comic-end"><strong>{episode}화 끝</strong><span>민수의 첫 경기는 다음 화에서 계속됩니다.</span></div><section className="review-box"><span className="review-eyebrow">EPISODE REVIEW</span><h2>{episode}화는 어떠셨나요?</h2>{reviewSaved?<div className="review-success"><strong>리뷰가 등록되었습니다.</strong><button onClick={()=>{setReviewSaved(false);setRating(0);setReview('')}}>다시 쓰기</button></div>:<><div className="star-rating">{[1,2,3,4,5].map(star=><button key={star} className={star<=rating?'selected':''} onClick={()=>setRating(star)} aria-label={`${star}점`}>★</button>)}</div><textarea value={review} onChange={event=>setReview(event.target.value)} placeholder="이 회차에 대한 감상을 남겨주세요." maxLength={500}/><div className="review-actions"><small>{review.length}/500</small><button disabled={!rating||!review.trim()} onClick={saveReview}>리뷰 등록</button></div></>}<button className="episode-back" onClick={()=>setEpisode(null)}>회차 목록으로</button></section></main>
}